# Generated by Django 5.1.6 on 2025-02-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_cat_age_remove_cat_breed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='cat',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.CharField(default='Tabby', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='description',
            field=models.TextField(default='dpwdpwdw', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.CharField(default='axax', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(verbose_name='Feeding date'),
        ),
    ]
